Add digi space register cmd
digi-project/digi pull request #31
Opened 2022-12-18 20:48 UTC by vakumar1

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
```

2022-12-18 22:33 UTC, silveryfu commented on cmd/digi/space/command.go
> +		kc, err := k8s.LoadKubeConfig();
Can remove ";"? Same below

2022-12-18 22:36 UTC, silveryfu requested changes
Looks good to me overall! Nice work. Left only a comment on APISERVER_IP.

A final nit: could you run `make fmt`and `git status` check if there are formatting changes (if there is, pls add to the PR)?

2022-12-18 22:36 UTC, silveryfu commented on scripts/register-space.sh
> +APISERVER_IP=$(kubectl -n kube-system get pod -l component=kube-apiserver -o=jsonpath="{.items[0].metadata.annotations.kubeadm\.kubernetes\.io/kube-apiserver\.advertise-address\.endpoint}")
I wonder if this IP is available in the kubeconfig? If so, might be easier to pass it in?

2022-12-19 04:12 UTC, vakumar1 commented on scripts/register-space.sh
> +APISERVER_IP=$(kubectl -n kube-system get pod -l component=kube-apiserver -o=jsonpath="{.items[0].metadata.annotations.kubeadm\.kubernetes\.io/kube-apiserver\.advertise-address\.endpoint}")
It looks like this IP isn't in the kubeconfig, only in the details for the pod running the apiserver.

2022-12-20 01:33 UTC, silveryfu commented on scripts/register-space.sh
> +APISERVER_IP=$(kubectl -n kube-system get pod -l component=kube-apiserver -o=jsonpath="{.items[0].metadata.annotations.kubeadm\.kubernetes\.io/kube-apiserver\.advertise-address\.endpoint}")
Thanks for checking @vakumar1  - sorry, by IP I meant a URL. There is a URL in the kubeconfig for the apiserver? Could you check if one can send request to that URL (in place of the APISERVER_IP obtained above)?

2022-12-20 01:37 UTC, silveryfu commented
LGTM. Thanks @vakumar1. 

> Use the URL in kubeconfig in place of `API_SERVER` obtained via `kubectl`

It'd be nice to confirm this and if so, we can use kubeconfig to pass in the URL and do the change in a future PR.

2022-12-20 01:37 UTC, merged