[cli] Add event and polling threads to lake driver to add pool info t…
digi-project/digi pull request #34
Opened 2022-12-28 04:27 UTC by runey333

…o lake spec

Signed-off-by: runey333 <arun.sundaresan1@gmail.com>

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
This PR has the lake driver set up a polling thread and an event thread, which both add pool information to the lake's spec to reconcile the model with the contents in the lake. The design is described here: https://github.com/digi-project/digi/issues/20. We use the Zed Lake API's /events endpoint to determine the pools that are in the lake, as well as to track their most recent commits in a dictionary stored in the driver. We also have the polling thread periodically update the timestamps, heads, and numbers of records in each pool (and reflect them in the lake's spec).

#### Which issue(s) this PR fixes:

Fixes https://github.com/digi-project/digi/issues/20

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
```

2022-12-28 19:44 UTC, silveryfu requested changes
I did a light pass; nice overall. Will revisit/take a closer look after the changes addressed.

Btw., would be nice if you include a list stats that will be added to this PR.

2022-12-28 19:44 UTC, silveryfu commented on lake/driver/handler.py
> +        #digi.logger.info("STUFF")
Might help to insert some informative logs or remove

2022-12-28 19:44 UTC, silveryfu commented on lake/driver/handler.py
> +def dict_from_data_line(data_line):
Perhaps data_line -> data_record or just record

2022-12-28 19:44 UTC, silveryfu commented on lake/driver/handler.py
> +def dict_from_data_line(data_line):
Would be nice to have a brief comment on what the input and output of this method would be like

2022-12-28 19:44 UTC, silveryfu commented on lake/driver/handler.py
> +def parse_delete_pool(data_line):
Perhaps move all the event parser to an event.py; handler.py is best kept for driver handlers only.

2022-12-28 19:44 UTC, silveryfu commented on lake/driver/handler.py
> +def check_attr_gen_patch_spec(new_spec):
The name of this method could be made more informative?

2022-12-28 19:44 UTC, silveryfu commented on lake/model.yaml
> +aggStats:
Just `stats`?

2022-12-28 19:44 UTC, silveryfu commented on lake/driver/handler.py
> +        count_query_response = requests.post(f"{ZED_LAKE_URL}/query", headers=headers, json=count_query_json_data)
There are several `requests` calls. I wonder if requests support long connection and/or we can use the pyzed client to send these queries (which should reuse a tcp connection)?

2022-12-29 18:49 UTC, runey333 commented on lake/model.yaml
> +aggStats:
Changed aggStats to stats.

2022-12-29 18:51 UTC, runey333 commented on lake/driver/handler.py
> +def check_attr_gen_patch_spec(new_spec):
changed to patch_existing_pools. @silveryfu do you find that more helpful?

2022-12-29 18:57 UTC, runey333 commented on lake/driver/handler.py
> +def parse_delete_pool(data_line):
Will include an event.py with parsing functions in the next commit

2022-12-29 19:10 UTC, runey333 commented on lake/driver/handler.py
> +def dict_from_data_line(data_line):
What do you mean by this @silveryfu?

2022-12-30 00:35 UTC, runey333 commented on lake/driver/handler.py
> +        count_query_response = requests.post(f"{ZED_LAKE_URL}/query", headers=headers, json=count_query_json_data)
Replaced requests with pyzed -- to come in the next commit

2022-12-30 00:35 UTC, runey333 commented on lake/driver/handler.py
> +        #digi.logger.info("STUFF")
Removed all commented-out digi.logger statements

2022-12-30 00:55 UTC, runey333 commented on lake/driver/handler.py
> +def dict_from_data_line(data_line):
Added some documentation to dict_from_data_line

2022-12-30 03:33 UTC, silveryfu commented on lake/driver/handler.py
> +def dict_from_data_line(data_line):
Sorry - what I meant was the "data_line" sounds a bit misleading to me and thought data record is what's taken in here. But on second thought, I would say probably `dict_from_event` is more proper?

2022-12-30 04:47 UTC, runey333 commented on lake/driver/handler.py
> +def dict_from_data_line(data_line):
This is the new docstring (this function is now in event.py):

```
"""
    This function turns zed outputs into dictionaries for more effective use. 
    
    Zed events output pairs of lines such as:
    
    event: pool-new
    data: {"pool_id": "1sMDXpVwqxm36Rc2vfrmgizc3jz"}
    (Taken from https://zed.brimdata.io/docs/lake/api#events)
        
    This function takes the "data" line or query output, passed in as bytes representing ZSON, and outputs a dictionary.
"""
```
The motivation for this name is that we use the "data" line that comes with each event.

2022-12-31 00:46 UTC, silveryfu commented on lake/driver/handler.py
> +def dict_from_data_line(data_line):
Ah - I see! Thanks. If the method is in say `event.py` and plus this docstring it would be very apparent 👍

2022-12-31 00:48 UTC, silveryfu requested changes
Nice - only two nits and we should be good to go. Thanks!

2022-12-31 00:48 UTC, silveryfu commented on lake/driver/handler.py
> +ZED_CLIENT = pyzed.Client(base_url=ZED_LAKE_URL)
Nit: perhaps `_zed_client` or simply `zed_client`

2022-12-31 00:48 UTC, silveryfu commented on lake/driver/handler.py
> +from event import dict_from_data_line, HEADS, POOL_NAME_MAP, PARSE_FUNCTION_MAP, NULL_COMMIT_ID
Nit: How about just import event? And refer to the methods/objects with event.x

2023-01-01 18:37 UTC, runey333 commented on lake/driver/handler.py
> +from event import dict_from_data_line, HEADS, POOL_NAME_MAP, PARSE_FUNCTION_MAP, NULL_COMMIT_ID
Resolved in latest commit

2023-01-01 18:37 UTC, runey333 commented on lake/driver/handler.py
> +ZED_CLIENT = pyzed.Client(base_url=ZED_LAKE_URL)
Changed to zed_client in latest commit

2023-01-01 19:24 UTC, silveryfu commented
Nice work @runey333.

2023-01-01 19:25 UTC, silveryfu approved these changes

2023-01-01 19:26 UTC, merged

2023-01-01 19:28 UTC, silveryfu commented
Note that the commits were not signed @runey333. We can bypass it for this PR but for future, perhaps try signing with `git commit -s`. Thanks!

2023-01-01 19:35 UTC, runey333 commented
I have been using `git commit -s` -- Is there something else I should be seeing here?:
<img width="452" alt="Screen Shot 2023-01-01 at 11 35 33 AM" src="https://user-images.githubusercontent.com/52219774/210182708-7e7c7d5e-aadb-4976-aa0e-7d55f5f81367.png">