Persistent Volume & Matter Ports
digi-project/digi pull request #36
Opened 2022-12-30 07:20 UTC by PotatoParser

#### What type of PR is this?

- Adds support for Digilite
  - `digi run lamp l1 -l matter`
- Adds support for Persistent Volume (local)
  - At runtime: `digi run lamp l1 --volume "/path:10Mi"`
  - At instance (`values.yaml`):
```yaml
group: example.digi.dev
image: 192.168.49.1:5000/lamp.v1.example.digi.dev:latest
imagepull: Always
kind: Lamp
mounter: false
name: lamp
namespace: default
plural: lamps
version: v1
# Persistent Volume
persistent_volume:
  size: 10Mi
  path: /test
```

#### What this PR does / why we need it:

- Includes critical port changes for mDNS in Matter protocol
- Lake and Matter both require a persistent volume

#### Which issue(s) this PR fixes:

Fixes #24 

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
Adds -l flag to add library
Adds --volume to add persistent volume at runtime
```

2022-12-30 16:23 UTC, silveryfu requested changes
Neat! Thanks @PotatoParser. I propose a few changes pls check out and let me know what you think!

2022-12-30 16:23 UTC, silveryfu commented on cmd/digi/digi/command.go
>  	initCmd.Flags().StringP("directory", "d", "", "Image directory")
Not part of this PR but could you help rename `Image directory` to `Profile directory`?

2022-12-30 16:23 UTC, silveryfu commented on cmd/digi/digi/command.go
> +	buildCmd.Flags().StringP("library", "l", "", "Digilite Library")
I wonder if this feature (providing digilite library) can be supplanted by a more generic API to replace the driver image? E.g., `-i` for `imagefile` or `dockerfile`.

2022-12-30 16:23 UTC, silveryfu commented on cmd/digi/digi/digi.go
> +			library = fmt.Sprintf("~/.digi/digilite/%s/Dockerfile", library)
The caller should pass in the dockerfile's path. I.e., not hard coding it below. For convenience, we can perhaps add _another_ flag that reuses the `-i` codepath to automatically use Digilite.

I'd point the path to the Digilite codebase (for now Digi's `make install` should better not place scripts from other codebase under .digi)

2022-12-30 16:23 UTC, silveryfu commented on cmd/digi/digi/digi.go
> +				"PROFILE":    profile,
Is this change made by `make fmt`?

2022-12-30 16:23 UTC, silveryfu commented on cmd/digi/digi/digi.go
> +		if len(persistentVolume) != 0 {
if persistentVolume != "" ?

2022-12-30 16:23 UTC, silveryfu commented on cmd/digi/digi/command.go
> +	runCmd.Flags().String("volume", "", "Persistent volume")
Perhaps make this a boolP flag and add `persistent-volume-size` and `persistent-volume-path` as two separate parameters each with default values?

2022-12-30 16:31 UTC, silveryfu commented
Ref #24 #25

2022-12-31 03:29 UTC, PotatoParser commented on cmd/digi/digi/digi.go
> +				"PROFILE":    profile,
I believe so, I can revert this though!

2022-12-31 03:31 UTC, PotatoParser commented on cmd/digi/digi/command.go
> +	runCmd.Flags().String("volume", "", "Persistent volume")
So somehing like:
```bash
digi run lamp l1 --pv true --pv-size 10Mi --pv-path /mt
```
?

2022-12-31 03:32 UTC, PotatoParser commented on cmd/digi/digi/digi.go
> +			library = fmt.Sprintf("~/.digi/digilite/%s/Dockerfile", library)
Ah, so do you recommend that the `digilite` library be preinstalled locally or have the Dockerfile be fetched during runtime with the `-i` flag?

2022-12-31 03:33 UTC, PotatoParser commented on cmd/digi/digi/command.go
>  	initCmd.Flags().StringP("directory", "d", "", "Image directory")
Sure thing!

2022-12-31 18:24 UTC, silveryfu commented on cmd/digi/digi/digi.go
> +				"PROFILE":    profile,
No, this is intened!

2022-12-31 18:28 UTC, silveryfu commented on cmd/digi/digi/command.go
> +	runCmd.Flags().String("volume", "", "Persistent volume")
Yes. The rationale is to decouple the role of the flag. Currently it serves both as an indicator of turning on volume _and_ the volume configuration. Besides, you can easily have default values for the configs.

Btw., -p (or -v) should indicate using pv, you don't need a "true" -- it is a bool; `--size` and `--path` are string.

2022-12-31 18:30 UTC, silveryfu commented on cmd/digi/digi/digi.go
> +			library = fmt.Sprintf("~/.digi/digilite/%s/Dockerfile", library)
The digilite codebase should be cloned locally (just as in mocks and examples). Definitely no Dockerfile fetching over the network.

My main point here is: your implementation above is mostly a generic "let's run the driver with this given Dockerfile", so let's make it that way (it itself is a useful feature) and build digilite linking on top of that.

2022-12-31 18:33 UTC, silveryfu commented on cmd/digi/digi/digi.go
> +			library = fmt.Sprintf("~/.digi/digilite/%s/Dockerfile", library)
So you will have two flags for build: `-i` for passing the dockerfile and `-d` or whatnot to link to digilite dockerfile on your local filesystem (`-d` can be a string flag with default path $GOPATH/digi.digi/digilite/...). If the digilite codebase doesn't exist, prompt to user instruction on what to do next (e.g. provide the path to the codebase or clone the codebase to the default location)

2022-12-31 18:36 UTC, silveryfu commented on driver/deploy/templates/actor.yaml
> +{{ if .Values.persistent_volume }}
@PotatoParser On second thought, the PersistVolume configs should better not be in the `actor.yaml` but on a separate say `volume.yaml`.

This is because actor.yaml may get overwritten by digis (e.g., lake/deploy/actor.yaml) and we want to provide default configs as much as possible.

2022-12-31 22:28 UTC, PotatoParser commented on cmd/digi/digi/digi.go
> +			library = fmt.Sprintf("~/.digi/digilite/%s/Dockerfile", library)
Sounds good!

2022-12-31 22:30 UTC, PotatoParser commented on driver/deploy/templates/actor.yaml
> +{{ if .Values.persistent_volume }}
Yeah I think that makes more sense

2023-01-03 03:19 UTC, PotatoParser commented on cmd/digi/digi/digi.go
> +			library = fmt.Sprintf("~/.digi/digilite/%s/Dockerfile", library)
Thoughts on merging these two into a generic `-i` where we target digilite as a priority and if it does not exist, then we use the path provided? ie: `-i matter` first checks to see if `$GOPATH/digi.dev/digilite/matter/Dockerfile` exists and if not, checks to see if `./matter` exists as an image. That way users don't confuse between using both `-i` and `-d`. In the future we omit referencing digilite and have it as a premade docker image: `FROM digilite:matter`

2023-01-03 03:20 UTC, silveryfu commented
Side-note: for future reference, pls update the PR's description to reflect the actual APIs when you get a chance. Thanks!

2023-01-03 03:21 UTC, PotatoParser commented
Will definitely update the description once I update with the changes!

2023-01-03 21:45 UTC, silveryfu commented on cmd/digi/digi/digi.go
> +			library = fmt.Sprintf("~/.digi/digilite/%s/Dockerfile", library)
Your proposal (`-i matter`) makes sense. However, just to clarify my point above: when `-d` is given, no `-i` is needed. The `-d` and `-i` have different semantics. `-i` is a generic passing docker image flag whereas `-d` says build with digilite. But what I missed was that within Digilite there are multiple platforms and potentially different images. In short, I like your proposal better.

Two minor suggestion: perhaps we don't to the second check on `./matter`?  And perhaps `-i digilite-matter` or make both `matter` and `digilite-matter` valid options.

2023-01-10 00:59 UTC, TarasPriadka commented on cmd/digi/digi/digi.go
> +			library = fmt.Sprintf("~/.digi/digilite/%s/Dockerfile", library)
I had an issue of resolving relative paths when working on my own PR to allow passing in Docker images(😨). Consider testing that case. Had a work using [this](https://github.com/TarasPriadka/digi/blob/f8aa7d8a7d5beeb994f38cc661dd38f720507816/cmd/digi/digi/digi.go#L169-L178).

2023-01-10 01:00 UTC, PotatoParser commented on cmd/digi/digi/digi.go
> +			library = fmt.Sprintf("~/.digi/digilite/%s/Dockerfile", library)
Thanks for the heads up! I'll definitely use the workDir for relative paths!

2023-01-10 02:25 UTC, TarasPriadka commented on cmd/digi/digi/digi.go
> +					filepath.Join(os.Getenv("GOPATH"), "src/digi.dev/digilite", imageFile, "Dockerfile"),
I think it may be slightly confusing to the users if they enter a path to an image, but `digi build` builds an image from digilite instead of using the path that they specified.

Maybe I am wrong, but lets say that you are working on a digi with the same name as a digi in digilite repo. You might be making changes to the driver and running build without realizing that you are building digilite image instead of the one that you intended to build. Do you think this is a potential issue?

2023-01-10 02:58 UTC, PotatoParser commented on cmd/digi/digi/digi.go
> +					filepath.Join(os.Getenv("GOPATH"), "src/digi.dev/digilite", imageFile, "Dockerfile"),
Hmmmm, I don't think it would be an issue since if you specify the dockerfile, it won't be able to use the digilite library. From https://github.com/digi-project/digi/pull/36#discussion_r1060257765, `digi build` should focus on the digilite library first, then if you possibly specified a folder, looks for the Dockerfile within that folder and finally the exact dockerfile. Though I see a possible error in that I should check to see if the path is a file, not just if it exists.

2023-01-10 03:29 UTC, TarasPriadka commented on cmd/digi/digi/digi.go
> +					filepath.Join(os.Getenv("GOPATH"), "src/digi.dev/digilite", imageFile, "Dockerfile"),
I imagine that people will often do something like `digi build -i somediginame/driver/Dockerfile` which might cause issues. However, this might not even be a frequent issue.

2023-01-10 04:38 UTC, silveryfu commented on cmd/digi/digi/command.go
> +	runCmd.Flags().Bool("enable-pv", false, "Enable persistent volume")
How about BoolP with `-p` as a shorthand? Or is the `-p` taken? Also, perhaps just call it `"persistent-volume"`

2023-01-10 04:55 UTC, silveryfu requested changes

2023-01-10 04:55 UTC, silveryfu commented on cmd/digi/digi/digi.go
> +					filepath.Join(os.Getenv("GOPATH"), "src/digi.dev/digilite", imageFile, "Dockerfile"),
Maybe I'm missing something so pls chime in: why isn't `image`/`imageFile` just a path to an actual file? 

In addition:
* Not looking closely but I think we should be able to handle relative path by joining with `workDir`?
* Digilite: @PotatoParser is there a reason why we don't use the `-d` design: https://github.com/digi-project/digi/pull/36#discussion_r1059669944

2023-01-10 04:55 UTC, silveryfu commented on cmd/digi/digi/command.go
> +	runCmd.Flags().Bool("enable-pv", false, "Enable persistent volume")
How about BoolP with -p as a shorthand? Or is the -p taken? Also, perhaps just call it "persistent-volume"

2023-01-10 04:55 UTC, silveryfu commented on driver/deploy/templates/actor.yaml
> -    name: {{ .Values.name }}
Is there a reason why this seemingly superfluous change happens?

2023-01-10 04:55 UTC, silveryfu commented on driver/deploy/templates/actor.yaml
> +  - port: 5540
Should we make these matter related ports optional? Not seeing why we need to enable matter ports for all digis as a default. What do you think?

One thing we can do is to provide a separate `actor.yaml` for digilite-matter.

2023-01-10 05:07 UTC, silveryfu commented
@PotatoParser I left comments. The PR is overall good. Thanks! 

The main issue is on the `-image` option.

Honestly, here is what I would do - I would split the PR into something like (in order):
* 1. "Adding persistent volume support"
* 2. "Allowing passing driver image on build"
* 3. "Integrating digilite-matter on build"

I think we can pass/merge 1. easily.
* For 2., let's just take the dockerfile as the command line parameter, no extra path enumerating 
* Then for 3., create a separate -d  option for integrate digilite.
The key here is: let's try not coupling 2. and 3. as I mentioned on the earlier comments.

2023-01-10 18:01 UTC, PotatoParser commented on driver/deploy/templates/actor.yaml
> -    name: {{ .Values.name }}
Oh! This is a mistake, it should not be here :sweat_smile:

2023-01-10 18:04 UTC, PotatoParser commented on cmd/digi/digi/command.go
> +	runCmd.Flags().Bool("enable-pv", false, "Enable persistent volume")
Good idea!

2023-01-10 18:05 UTC, PotatoParser commented on driver/deploy/templates/actor.yaml
> +  - port: 5540
Perhaps in this instance we should have the digilite library also override the default template.

2023-01-10 18:08 UTC, PotatoParser commented
The main reasoning behind the usage of `-i` for both digilite images and target image files is because these two things are exclusive. Doing `-d matter -i /path/to/image/Dockerfile` has undefined behavior; `-d matter` will override the base image with `/digi.dev/digilite/matter/Dockerfile`, but at the same time, you would be doing a `-i /path/to/image/Dockerfile` which will also override the image.

2023-01-10 18:11 UTC, PotatoParser commented on driver/deploy/templates/actor.yaml
> -    name: {{ .Values.name }}
I'm not too sure why this was marked as a change, most likely because I had deleted the persistent volume inclusion before it

2023-01-24 21:19 UTC, silveryfu commented
> TBD @silveryfu review post Feb 2

2023-01-31 07:42 UTC, silveryfu commented on driver/deploy/templates/actor.yaml
> +  - port: 5540
Yes. @PotatoParser I don't feel we should add matter and mdns in the default driver's port. Is there a way we override these as well?

2023-01-31 07:45 UTC, silveryfu commented
Lgtm overall. Nice work @PotatoParser. 

There is one issue about opening matter and mdns ports on the driver by default. Could you open an Issue for this? (making it optional and generate only when `-d` is enabled on run)

2023-01-31 07:46 UTC, merged