Improve pool information in lake spec
digi-project/digi pull request #41
Opened 2023-01-14 19:25 UTC by runey333

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
This PR adds additional information to the lake spec. 
1. Add human-readable names to each pool entry
2. Make the polling interval an attribute configurable with digi edit
3. Add a default for the pool count

#### Which issue(s) this PR fixes:

Fixes https://github.com/digi-project/digi/issues/39

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note NONE
```

2023-01-18 12:10 UTC, silveryfu requested changes
Nice enhancements over lake!

2023-01-18 12:10 UTC, silveryfu commented on lake/crd.yaml
> +                  poll_interval_seconds:
Nice. A nit: how about just `poll_interval`? Btw., I think CRD allows adding description to properties (e.g. where you can comment on the "unit" being second), though `gen.py` currently doesn't support it.

2023-01-18 12:10 UTC, silveryfu commented on lake/driver/event.py
> +        HEADS_LOCK.acquire()
Is it possible to use `with` statement here? E.g. `with LOCK` ... if pool_id in HEADs

2023-01-18 12:10 UTC, silveryfu commented on lake/driver/handler.py
> +    curr_spec, _, _ = digi.util.get_spec("digi.dev", "v1", "lakes", "lake", "default")
I wonder if it's cleaner to get the spec from `digi.model` (this reads the curr_spec from the reconciler, I think), so that we don't need to hardcode the digi's gvr, if that makes sense.

2023-01-19 17:08 UTC, runey333 commented on lake/driver/handler.py
> +    curr_spec, _, _ = digi.util.get_spec("digi.dev", "v1", "lakes", "lake", "default")
@silveryfu where is digi.model defined? How would we get a spec from there?

2023-01-19 18:00 UTC, runey333 commented on lake/driver/event.py
> +        HEADS_LOCK.acquire()
@silveryfu what advantage does a `with` statement provide?

2023-01-19 18:25 UTC, silveryfu commented on lake/driver/event.py
> +        HEADS_LOCK.acquire()
Cleaner?

2023-01-19 18:26 UTC, silveryfu commented on lake/driver/handler.py
> +    curr_spec, _, _ = digi.util.get_spec("digi.dev", "v1", "lakes", "lake", "default")
https://github.com/digi-project/digi/blob/main/driver/digi/control.py `digi.model.get()`

2023-01-19 18:35 UTC, runey333 commented on lake/crd.yaml
> +                  poll_interval_seconds:
Editing in next commit.

2023-01-19 19:04 UTC, runey333 commented on lake/driver/event.py
> +        HEADS_LOCK.acquire()
Replaced explicit lock acquires/releases using with statement as shown here: [](https://www.bogotobogo.com/python/Multithread/python_multithreading_Using_Locks_with_statement_Context_Manager.php)

2023-01-19 19:26 UTC, runey333 commented on lake/driver/handler.py
> +    curr_spec, _, _ = digi.util.get_spec("digi.dev", "v1", "lakes", "lake", "default")
@silveryfu Could we also just use `digi.g`, `digi.v`, and `digi.r` instead of hardcoding? For example this:
`cur_gen, r, e = digi.util.check_gen_and_patch_spec(
            digi.g, digi.v, digi.r, digi.n, digi.ns,
            view, gen)`
 is used in control.py.

2023-01-20 03:24 UTC, merged