Add Expose Command
digi-project/digi pull request #45
Opened 2023-02-11 02:31 UTC by runey333

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
This PR adds an expose command to the CLI. This command takes a digi name and a port to expose on, and creates a NodePort using the specified port, along with the port and targetport of the service that was already created for that digi. This makes it easier to publicly expose digis, particularly lakes. 

#### Which issue(s) this PR fixes:

Fixes #42 

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```Adds an additional command to the CLI.
```

2023-02-11 02:53 UTC, silveryfu requested changes

2023-02-11 02:53 UTC, silveryfu commented on cmd/digi/digi/digi.go
> +		k8s_clientset, err := k8s.NewClientSet()
Let's keep consistent using camel style?

2023-02-11 02:53 UTC, silveryfu commented on cmd/digi/digi/digi.go
> +		//export PORT=$(kubectl get service l2 -o jsonpath='{.spec.ports[0].port}')
Do we need these in the comments?

2023-02-11 03:12 UTC, runey333 commented on cmd/digi/digi/digi.go
> +	Use:     "expose NAME NODEPORT",
What do you mean by this @silveryfu?

2023-02-11 03:12 UTC, runey333 commented on cmd/digi/digi/digi.go
> +		k8s_clientset, err := k8s.NewClientSet()
will refactor

2023-02-11 03:12 UTC, runey333 commented on cmd/digi/digi/digi.go
> +		//export PORT=$(kubectl get service l2 -o jsonpath='{.spec.ports[0].port}')
will remove

2023-02-12 01:38 UTC, silveryfu commented on cmd/digi/digi/digi.go
> +	Use:     "expose NAME NODEPORT",
If you look at the example in https://kubernetes.io/docs/concepts/services-networking/service/#nodeport-custom-port, there is a `port`, `targetport`, and a `nodeport`. I wonder if your command want to allow the user to specify all these options.

2023-02-12 01:39 UTC, silveryfu commented on cmd/digi/digi/digi.go
> +	Use:     "expose NAME NODEPORT",
Besides, it could be ambiguous which port value to specify in the command (among the three options).

2023-02-12 02:06 UTC, runey333 commented on cmd/digi/digi/digi.go
> +	Use:     "expose NAME NODEPORT",
In that case, I can replace this with three flags: --port, --targetport, and --nodeport. If --port or --targetport is not specified, we can just use the values from the service that is already created for the digi. If --targetport isn't specified, k8s will pick one on its own

2023-02-13 02:32 UTC, silveryfu commented on cmd/digi/digi/command.go
> +	exposeCmd.Flags().IntP("targetPort", "t", -1, "targetPort")
Do we have to use default value here? `-1` doesn't seem indicative nor appropriete.

2023-02-13 02:39 UTC, silveryfu commented on cmd/digi/digi/digi.go
> +	"time"
Move this to the first group?

2023-02-13 02:41 UTC, silveryfu commented on cmd/digi/digi/digi.go
> +		passedNodePort := nodePortFlag
Then use `0` as the default value?

2023-02-13 02:42 UTC, silveryfu requested changes

2023-02-13 02:42 UTC, silveryfu commented on cmd/digi/digi/digi.go
> +				port = int(currService.Spec.Ports[0].Port)
Supports only the first port?

2023-02-13 02:45 UTC, runey333 commented on cmd/digi/digi/command.go
> +	exposeCmd.Flags().IntP("targetPort", "t", -1, "targetPort")
Changed the default to 0

2023-02-13 02:45 UTC, runey333 commented on cmd/digi/digi/digi.go
> +		passedNodePort := nodePortFlag
Changed the default to 0

2023-02-13 02:46 UTC, runey333 commented on cmd/digi/digi/digi.go
> +	"time"
Moved to first group

2023-02-13 03:49 UTC, silveryfu commented
Lgtm. Nice!

2023-02-13 03:49 UTC, merged