Add redpanda digi
digi-project/digi pull request #54
Opened 2023-03-15 21:39 UTC by vakumar1

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Add a Redpanda broker digi that allows consumers/producers to read/write from/to "topics." The broker endpoint is hardcoded and was initially created as a utility digi in the anysource dspace.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

2023-03-15 22:07 UTC, JamsheedMistri requested changes
Are you planning on running this as a digi space? If so, additional modifications are needed in `/Makefile`, `/cmd/digi/digi/digi.go`, `/cmd/digi/space/command.go`, and `/model/Makefile`. See my headscale PR [here](https://github.com/digi-project/digi/pull/46/files) for reference.

2023-03-15 22:07 UTC, JamsheedMistri commented on message/redpanda/deploy/values.yaml
> +image: vakumar23/redpanda.v1.message.digi.dev:latest
Was this built with `digi build -a` for cross-platform compatibility??

2023-03-15 22:07 UTC, JamsheedMistri commented on message/redpanda/driver/handler.py
> +ADVERTISED_BROKERS = "dspace.anysource.io:30292"
Why is this hardcoded?

2023-03-15 22:07 UTC, JamsheedMistri commented on message/redpanda/driver/handler.py
> +        digi.logger.info("unable to start rpk")
Is the digi called `redpanda` or `rpk`? IMO it should be consistent for readability. If it's `redpanda`, then this log message should read `"unable to start redpanda"`.

2023-03-15 22:07 UTC, JamsheedMistri commented on message/redpanda/driver/handler.py
> +    digi.logger.info("started rpk")
Same as above

2023-03-15 22:24 UTC, silveryfu commented on message/redpanda/driver/handler.py
> +ADVERTISED_BROKERS = "dspace.anysource.io:30292"
We should perhaps make this configurable via the redpanda's model

2023-03-26 06:24 UTC, silveryfu commented on message/redpanda/driver/handler.py
> +ADVERTISED_BROKERS = "dspace.anysource.io:30292"
@vakumar1 shall we fix this (add to the model) and then we can merge?

2023-03-27 06:54 UTC, JamsheedMistri approved these changes
LGTM!

2023-04-03 20:33 UTC, merged