Add Sourcer to DSpace
digi-project/digi pull request #55
Opened 2023-03-19 21:11 UTC by runey333

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
```

2023-03-19 23:13 UTC, silveryfu requested changes

2023-03-19 23:13 UTC, silveryfu commented on driver/digi/data/router.py
> +    def source_helper(self, source_quantifier):
call this `resolve_source`

2023-03-19 23:13 UTC, silveryfu commented on driver/digi/data/router.py
> +            if ig.get("pause", False) or name == "sourcer":
why this `name == "sourcer"`

2023-03-19 23:13 UTC, silveryfu commented on driver/digi/data/router.py
> +            if ig.get("pause", False) or name == "sourcer":
If we dealing with sourcer specific logic inside an app driver, it makes the code very difficult to reason about.

2023-03-19 23:13 UTC, silveryfu commented on driver/digi/data/router.py
> +        use_sourcer = ("sourcer" in config) and ("use_sourcer" in config["sourcer"]) and config["sourcer"]["use_sourcer"]
And sourcer = config.get("sourcer", False)

2023-03-19 23:13 UTC, silveryfu commented on driver/digi/data/router.py
>              for s in ig.get("sources", []):
See https://github.com/digi-project/digi/issues/56. Let's handle only the case with `source` above

2023-03-19 23:13 UTC, silveryfu commented on model/Makefile
> +	kubectl exec -it `kubectl get pod --field-selector status.phase=Running -l name=$(NAME) -oname` -- /bin/$(SHELL_BIN)
What does this do? The connect command is for port forwarding

2023-03-19 23:13 UTC, silveryfu commented on model/Makefile
> +	WORKDIR=$(DIGIHOME) digi run sourcer sourcer --no-pool
Start sourcer separately from lake

2023-03-19 23:13 UTC, silveryfu commented on model/Makefile
> -.PHONY: start-net stop-net
Why we remove the headscale?

2023-03-19 23:13 UTC, silveryfu commented on model/gen.py
> +  sourcer:
As comment above, just make this a single bool

2023-03-19 23:13 UTC, silveryfu commented on model/gen.py
> +    properties:
We should be modifying the _ingress_attr below

2023-03-19 23:13 UTC, silveryfu commented on sourcer/deploy/cr.yaml
> +    registry: |
Let's not commit testing data to the repo; we can create a /test to include these testing yaml and `digi space start sourcer -f` from the config

2023-03-22 02:42 UTC, runey333 commented on driver/digi/data/router.py
> +            if ig.get("pause", False) or name == "sourcer":
Removed

2023-03-22 02:42 UTC, runey333 commented on driver/digi/data/router.py
> +        use_sourcer = ("sourcer" in config) and ("use_sourcer" in config["sourcer"]) and config["sourcer"]["use_sourcer"]
Changed to have one use_sourcer per ingress

2023-03-22 02:43 UTC, runey333 commented on driver/digi/data/router.py
> +            pass
I think this should be an info -- does an error log cause any impact in the functionality of the digi (asking since we should still keep functioning if we have to resort to parse_source)

2023-03-22 02:44 UTC, runey333 commented on driver/digi/data/router.py
> +import requests
changed

2023-03-22 02:44 UTC, runey333 commented on driver/digi/data/router.py
> +    def source_helper(self, source_quantifier):
changed

2023-03-22 03:43 UTC, runey333 commented on driver/digi/data/router.py
> +            sourcer_response_json = sourcer_response.json() #list of the form [lake url, sources, success]
changed

2023-03-22 03:46 UTC, runey333 commented on model/gen.py
> +  sourcer:
changed to have one use_sourcer per ingress

2023-03-22 03:46 UTC, runey333 commented on model/gen.py
> +    properties:
changed to have one use_sourcer per ingress

2023-03-22 04:07 UTC, runey333 commented on Makefile
> +	@rm $(HOMEDIR)/lake $(HOMEDIR)/sourcer $(HOMEDIR)/space $(HOMEDIR)/message $(HOMEDIR)/net $(HOMEDIR)/sidecar >/dev/null 2>&1 || true
moved to space and removed sourcer

2023-03-22 04:33 UTC, runey333 commented on model/Makefile
> +	WORKDIR=$(DIGIHOME) digi run sourcer sourcer --no-pool
made separate start-sourcer and stop-sourcer commands

2023-03-22 04:33 UTC, runey333 commented on model/Makefile
> -.PHONY: start-net stop-net
added back

2023-03-22 17:44 UTC, runey333 commented on model/Makefile
> +	kubectl exec -it `kubectl get pod --field-selector status.phase=Running -l name=$(NAME) -oname` -- /bin/$(SHELL_BIN)
restored

2023-03-22 22:07 UTC, runey333 commented on sourcer/deploy/cr.yaml
> +    registry: |
Added a -f option which is passed to the -d of digi run when running a sourcer in start-space

2023-03-22 22:08 UTC, runey333 commented on driver/digi/data/router.py
>              for s in ig.get("sources", []):
Removed code to handle sources

2023-03-26 06:15 UTC, silveryfu commented on model/Makefile
> +	WORKDIR=$(DIGIHOME) digi run space/sourcer sourcer -d $(CR) --no-pool
Is CR always set? If not, will `-d` report an error?

2023-03-26 06:17 UTC, silveryfu commented on model/Makefile
> +start-space: | start-lake start-sourcer # ...
You would probably want to add sourcer into the list of dSpace controllers: https://github.com/digi-project/digi/blob/20ee6e10c3cc3a5f7b16a1616f9e8084a1c45c87/cmd/digi/space/command.go#L18

Btw., let's not make sourcer start off by default until a later point (e.g. next release)

2023-03-26 06:20 UTC, silveryfu commented on driver/digi/data/router.py
> -            for s in ig.get("sources", []):
My mistake - let's still handle the case `sources` in this PR. We gonna remove `sources` in future, but not this one. Please add back the sources case. Thanks!

2023-03-26 06:22 UTC, silveryfu commented
Thanks for addressing the comments. @runey333 Nicely done overall. Left a few comments. After that we are good to go.

2023-03-26 06:23 UTC, silveryfu commented
Btw., your commits were not signed - it'd be nice to sign them in future if possible!

2023-03-26 19:49 UTC, runey333 commented
> Btw., your commits were not signed - it'd be nice to sign them in future if possible!

I've been using -s for them and they do say "signed off by arun.sundaresan1@gmail.com". Is there something else I need to do?

2023-03-26 19:55 UTC, runey333 commented on driver/digi/data/router.py
> -            for s in ig.get("sources", []):
Added this back

2023-03-26 19:56 UTC, runey333 commented on model/Makefile
> +	WORKDIR=$(DIGIHOME) digi run space/sourcer sourcer -d $(CR) --no-pool
It should be. We have this:
`ifndef CR
override CR = cr.yaml
endif`
at the start of the Makefile so CR should be set to default if it isn't already passed in.

2023-03-26 20:00 UTC, runey333 commented on model/Makefile
> +	WORKDIR=$(DIGIHOME) digi run space/sourcer sourcer -d $(CR) --no-pool
btw the CR is passed in as a parameter to start-space

2023-03-26 20:20 UTC, runey333 commented on model/Makefile
> +start-space: | start-lake start-sourcer # ...
Added sourcer to list of controllers. In this case should I add a boolean flag that starts the sourcer?

2023-03-26 20:57 UTC, silveryfu commented on model/Makefile
> +start-space: | start-lake start-sourcer # ...
The value of that `map[strong]bool` is not currently used, we can just set it to `true`

2023-04-03 21:13 UTC, silveryfu commented on model/Makefile
> +	WORKDIR=$(DIGIHOME) digi run space/sourcer sourcer -d $(CR) --no-pool
Should we remove `--no-pool`

2023-04-05 01:22 UTC, silveryfu commented on cmd/digi/space/command.go
> +		registry_file, _ := cmd.Flags().GetString("registry-file")
Use camel case?

2023-04-05 01:24 UTC, silveryfu commented on cmd/digi/space/command.go
> +	startCmd.Flags().StringP("registry-file", "f", "cr.yaml", "Specify a file with registry data")
"Specify a file containing registry data"

2023-04-05 01:46 UTC, silveryfu requested changes

2023-04-05 01:46 UTC, silveryfu commented on model/Makefile
> +.PHONY: query conn-lake conn-lake-bg conn-lake-stop start-lake start-sourcer stop-lake stop-sourcer load
Can we separate the sourcer from the lake? E.g. add a new .PHONY and put the sourcer stuff in that block

2023-04-05 01:46 UTC, silveryfu commented on model/gen.py
> +              attrs[_n] = yaml.load(_attr_tpl.format(name=_n, datatype=t),
Is there a different way to handle this? Ideally we don't want to handle a digi specific case deep down in the gen.py code.

2023-04-05 01:46 UTC, silveryfu commented on space/sourcer/driver/handler.py
> +
Make the space between methods consistent?

2023-04-05 01:46 UTC, silveryfu commented on driver/digi/data/router.py
> +            source_list = []
```
for s in set(ig.get("source", []) + ig.get("sources", [])):
     if use_sourcer: ...
```

2023-04-05 01:46 UTC, silveryfu commented on driver/digi/data/router.py
>              # TBD deduplicate sources
Remove this comment (the above change deduplicate the sources already)

2023-04-05 01:54 UTC, runey333 commented on model/gen.py
> +              attrs[_n] = yaml.load(_attr_tpl.format(name=_n, datatype=t),
I just tested it out removing this if statement (but keeping the block inside it as before) and the crd is the same as before.

2023-04-05 04:13 UTC, silveryfu commented
Nice work - thanks @runey333!

2023-04-05 04:14 UTC, merged