[cli] Add secrets, and add change EMQX digi to use secrets
digi-project/digi pull request #57
Opened 2023-04-06 01:55 UTC by JamsheedMistri

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Adds the ability for digi developers to add secrets to their digis. These secret files are not committed to the digi code, and can be used for configuration or sensitive information (i.e. username/password, API key, etc).

The digi developer can instruct users to create a secret file in a brand-new `secrets` directory under the digi home directory, where they can store their secrets. Finally, the users can run their digis using the secrets file with a new CLI argument `-s`, which takes a secrets file and applies it to the digi kubernetes resource.

As a proof of concept, this feature is implemented in the EMQX digi space.

#### Does this PR introduce a user-facing change?
```release-note
Adds the ability for digi developers to add secrets to their digis. These secret files are not committed to the digi code, and can be used for configuration or sensitive information (i.e. username/password, API key, etc).

The digi developer can instruct users to create a secret file in a brand-new `secrets` directory under the digi home directory, where they can store their secrets. Finally, the users can run their digis using the secrets file with a new CLI argument `-s`, which takes a secrets file and applies it to the digi kubernetes resource.
```

2023-04-06 15:56 UTC, silveryfu requested changes
Solid work - an important feature implemented and documented well. Nice. 

Left some comments mainly on handling commands in the two Makefiles.

2023-04-06 15:56 UTC, silveryfu commented on Makefile
> +	@mkdir $(HOMEDIR)/emqx >/dev/null 2>&1 || true
I wonder if this should be under `$(HOMEDIR)/message/emqx`, though I might miss some considerations here; if. so, could you elaborate? Likewise, the line above for headscale, I wonder whether we need it given the `$(HOMEDIR)/net`?

2023-04-06 15:56 UTC, silveryfu commented on message/emqx/deploy/templates/actor.yaml
> -    digi.dev/type: kernel
Should we keep this label? It can have many labels.

2023-04-06 15:56 UTC, silveryfu commented on model/Makefile
> +	WORKDIR=$(DIGIHOME) digi run message/emqx emqx -s $(DIGIHOME)/secrets/emqx-dash-auth.yaml
Is it still ok that the secret is not provided? If we want to support the non-auth mode, perhaps separate this Makefile command into two: `start-emqx` and `start-emqx-auth` where the latter is used when `-s` is used.

2023-04-06 15:56 UTC, silveryfu commented on model/Makefile
> +	kubectl apply -f $(SECRETS) >/dev/null || true && \
Is there a way we handle this `apply` in the same `run.yaml` generated by the helm template? E.g., copying the secret file to where the helm is processing the run.yaml - this is the temporary bulid dir I believe. See: https://github.com/digi-project/digi/blob/fc786c56ca786105e1592fadab16d20b5424f05e/model/Makefile#L103

Also this extra kubectl invocation may add visible latency to the `digi run command`.

2023-04-06 15:56 UTC, silveryfu commented on model/README.md
> +One of the ways you can utilize your secret is by adding it as an environment variable to your digi. Under your `env` group, you can specify that an enviornment variable should be pulled from a secre
Make this a bullet point under L26?

2023-06-12 05:50 UTC, JamsheedMistri commented on Makefile
> +	@mkdir $(HOMEDIR)/emqx >/dev/null 2>&1 || true
`$(HOMEDIR)/message/emqx` already exists; `$(HOMEDIR)/message` is the digi directory for the `message` digi. `$(HOMEDIR)/emqx` is the location where the persistent volume data is stored for the `message` digi.

I do think the naming convention is confusing, something along the lines of `message` and `message-vol` might make more sense, but I didn't come up with this convention, I believe I followed the naming convention from another digi space. I also used this naming convention for the `headscale` digi space, so if we want to rename, we should also reflect those changes in the `headscale` digi space as well. Let me know what you think.

2023-06-12 06:05 UTC, JamsheedMistri commented on model/Makefile
> +	WORKDIR=$(DIGIHOME) digi run message/emqx emqx -s $(DIGIHOME)/secrets/emqx-dash-auth.yaml
In the driver, `-s` will run `kubectl apply -f $(SECRETS) >/dev/null || true` ([L174](https://github.com/digi-project/digi/pull/57/files#diff-228c9bc0b8504fd7655bff948cdedb5777dc99d2349efc773dd9bd288a600e63R174)). If the secret file doesn't exist or is invalid, nothing happens and the digi run command continues as normal without the secrets. I've tested this.

Both variables are optional ([L57](https://github.com/digi-project/digi/pull/57/files#diff-95ec3413966a3d5a737a06f62ef069c2e3eb3aa393cff9a04e01036a9e9b190bR57), [L63](https://github.com/digi-project/digi/pull/57/files#diff-95ec3413966a3d5a737a06f62ef069c2e3eb3aa393cff9a04e01036a9e9b190bR63)), so if they are not provided due to the above scenario, there is no issue. The digi handler will attempt to retrieve the environment variables, and if they don't exist, they'll use a default value instead ([L8-9](https://github.com/digi-project/digi/pull/57/files#diff-e132793bd29a03cb60be34445fe13e4cf947a0feb8e6210bb9ef02206d4ae212R8-R9)).

2023-06-12 06:40 UTC, silveryfu commented on Makefile
> +	@mkdir $(HOMEDIR)/emqx >/dev/null 2>&1 || true
@JamsheedMistri You are right -- I think your proposal of "x-vol" makes sense. I also find the naming convention a bit misleading -- right now we have two message brokers (emqx and redpanda), I think the .digi directories should reflect these changes. Likewise, as you point out, we should also reflect the changes in the net/headscale. 

Do you think you can factor/refactor these changes in this PR?

2023-06-12 06:42 UTC, silveryfu commented on model/Makefile
> +	WORKDIR=$(DIGIHOME) digi run message/emqx emqx -s $(DIGIHOME)/secrets/emqx-dash-auth.yaml
Thanks for the clarification. I think it's just a "style" issue -- for some reason I found surfacing any CLI option as much as possible easier to reason about (in this case, making start-emqx-auth explicit rather than relying on the internal behavior of`-s`).  Either works for me!

2023-06-12 06:46 UTC, silveryfu commented on model/Makefile
> +	kubectl apply -f $(SECRETS) >/dev/null || true && \
The point is we should reduce the number of `kubectl` cli invocation in `digi run` (each adds ~50-100ms latency). If we can put the secrets yaml inside run.yaml, we can avoid introducing another such invocation.

2023-06-16 06:45 UTC, JamsheedMistri commented on Makefile
> +	@mkdir $(HOMEDIR)/emqx >/dev/null 2>&1 || true
@silveryfu After looking into this more, the reason the volume is called `emqx` is because we use `{{ .Values.name }}` as the Persistent Volume Claim name. If we hardcode this to `message-vol`, it may alter the cohesiveness of @PotatoParser's PVC logic, which I believe assumes that the PVC is named after the digi's name.

Should we hardcode it or leave it as-is?

2023-06-16 21:02 UTC, JamsheedMistri commented
@silveryfu All requested changes added:

- `digi space start emqx-auth` for starting emqx space with authentication enabled
- Persistent volumes moved to `~/.digi/pv/`
- Secrets application moved to run.yaml

2023-06-19 05:59 UTC, silveryfu commented
@JamsheedMistri Thanks. All's good except for one question (probably due to previous miscommunication): is there a reason why the CLI's command is `digi space start emqx-auth` not say `digi space start -s [OPTIONAL_SECRET] emqx`?

2023-06-20 19:04 UTC, silveryfu commented
@JamsheedMistri Nice! Merged!

2023-06-20 19:04 UTC, merged